/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./components/Logo.vue')['default']
    MaterialSymbolsExtension: typeof import('~icons/material-symbols/extension')['default']
    SharedSubtitle: typeof import('./components/SharedSubtitle.vue')['default']
  }
}
